import Link from "next/link";
import { ArrowLeft, Scale } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
      <div className="container mx-auto max-w-4xl px-4 py-12">
        {/* Back Button */}
        <Link href="/">
          <Button variant="ghost" className="mb-8 text-slate-400 hover:text-white">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </Link>

        {/* Header */}
        <div className="mb-12 rounded-2xl border border-purple-500/30 bg-purple-500/10 p-8 text-center">
          <div className="mb-4 flex justify-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-purple-500/20">
              <Scale className="h-8 w-8 text-purple-400" />
            </div>
          </div>
          <h1 className="mb-4 text-4xl font-bold text-white md:text-5xl">
            Terms of Service
          </h1>
          <p className="text-lg text-purple-300">
            Last updated: March 30, 2026
          </p>
        </div>

        {/* Content */}
        <div className="space-y-8">
          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">1. Acceptance of Terms</h2>
            <p className="text-slate-400">
              By accessing and using PredictionPro (&quot;the Platform&quot;), you agree to be bound by these 
              Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Platform.
            </p>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">2. Description of Service</h2>
            <p className="text-slate-400">
              PredictionPro is a decentralized prediction market platform built on the Solana blockchain. 
              Users can create markets on various topics, trade YES/NO tokens, and potentially earn fees 
              based on market outcomes. The Platform utilizes Bags Protocol for token creation and trading.
            </p>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">3. Market Creation & Fees</h2>
            <p className="text-slate-400">
              Market creators on PredictionPro:
            </p>
            <ul className="mt-4 list-inside list-disc space-y-2 text-slate-400">
              <li>Set the initial liquidity for their markets</li>
              <li>Earn 70% of all trading fees generated by their market</li>
              <li>Are responsible for ensuring market questions are clear and resolvable</li>
              <li>Must resolve markets fairly based on publicly verifiable outcomes</li>
            </ul>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">4. Trading Rules</h2>
            <p className="text-slate-400">
              Users who trade on PredictionPro:
            </p>
            <ul className="mt-4 list-inside list-disc space-y-2 text-slate-400">
              <li>Must connect a compatible Solana wallet (Phantom, Solflare, etc.)</li>
              <li>Understand that trading involves financial risk</li>
              <li>Agree that all trades are final and irreversible</li>
              <li>Must be of legal age in their jurisdiction to participate</li>
              <li>Are responsible for any taxes arising from trading activity</li>
            </ul>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">5. Prohibited Activities</h2>
            <p className="text-slate-400">
              Users may not:
            </p>
            <ul className="mt-4 list-inside list-disc space-y-2 text-slate-400">
              <li>Create markets with the intent to manipulate outcomes</li>
              <li>Use false or misleading information in market descriptions</li>
              <li>Engage in wash trading or artificial volume</li>
              <li>Create markets related to illegal activities</li>
              <li>Attempt to exploit smart contracts or the Platform</li>
              <li>Harass, threaten, or intimidate other users</li>
            </ul>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">6. Market Resolution</h2>
            <p className="text-slate-400">
              Market creators are responsible for resolving their markets. Resolution should be based on 
              verifiable, publicly available information. If a creator fails to resolve a market within 
              30 days of the event outcome, PredictionPro reserves the right to resolve or archive the market.
            </p>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">7. Disclaimer of Warranties</h2>
            <p className="text-slate-400">
              THE PLATFORM IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND. 
              WE DO NOT GUARANTEE THAT THE PLATFORM WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. 
              WE ARE NOT RESPONSIBLE FOR ANY LOSSES ARISING FROM USE OF THE PLATFORM.
            </p>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">8. Limitation of Liability</h2>
            <p className="text-slate-400">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, PREDICTIONPRO AND ITS DEVELOPERS SHALL NOT BE 
              LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING 
              FROM OR RELATED TO USE OF THE PLATFORM.
            </p>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">9. Changes to Terms</h2>
            <p className="text-slate-400">
              We reserve the right to modify these Terms at any time. Changes will be effective immediately 
              upon posting on the Platform. Your continued use of the Platform after changes constitutes 
              acceptance of the modified Terms.
            </p>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-white">10. Contact</h2>
            <p className="text-slate-400">
              For questions about these Terms, please contact us at:
            </p>
            <ul className="mt-4 list-inside space-y-2 text-slate-400">
              <li>Twitter: @predictionproio</li>
              <li>Discord: Join our community server</li>
              <li>Website: https://predictionpro.io</li>
            </ul>
          </section>
        </div>

        {/* Agreement */}
        <div className="mt-12 text-center">
          <p className="mb-6 text-sm text-slate-500">
            By using PredictionPro, you acknowledge that you have read, understood, and agree to these Terms of Service.
          </p>
          <Link href="/">
            <Button className="bg-gradient-to-r from-[#9945FF] to-[#14F195] text-white hover:opacity-90">
              I Agree - Return to Home
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
